---
#YAML FILE START

__main__: "DEBUG"

##### DB SYNC #####
rfb_cycler_db_sync: "INFO"
db_sync.src.rfb_cycler_db_sync: "DEBUG"
##### DRV ######
rfb_scpi_sniffer: "DEBUG"

##### SYS #####
rfb_logger_tool: "ERROR"
rfb_shared_tool: "ERROR"
rfb_config_tool: "ERROR"

file_handlers: {}