---
#YAML FILE START
APP.APP_MODULE: "CRITICAL" #APP/APP_MODULE/APP_EXAMPLE.py

__main__: "INFO"

##### DEV ######
rfb_cycler_cu_manager: "DEBUG"
cu_manager.src.rfb_cycler_cu_manager: "DEBUG"

##### DRV ######
rfb_driver_mqtt: "ERROR"
rfb_can_sniffer: "ERROR"
rfb_scpi_sniffer: "ERROR"

##### SYS #####
rfb_logger_tool: "ERROR"
rfb_shared_tool: "ERROR"
rfb_config_tool: "ERROR"

file_handlers: {}