---
#YAML FILE START
APP.APP_MODULE: "CRITICAL" #APP/APP_MODULE/APP_EXAMPLE.py
test_mid_dabs: "DEBUG"

__main__: "INFO"

##### DEV ######
cu_broker_client: "INFO"
cu_manager: "INFO"
detect: "INFO"
register: "INFO"

##### DRV ######
rfb_driver_epc: "ERROR"
rfb_driver_db: "ERROR"
rfb_driver_bases : "ERROR"
rfb_driver_ea: "ERROR"
rfb_driver_rs: "ERROR"
rfb_driver_bk: "ERROR"
rfb_driver_bms: "ERROR"
rfb_driver_flow : "ERROR"
rfb_can_sniffer: "ERROR"
rfb_scpi_sniffer: "ERROR"

##### SYS #####
rfb_logger_tool: "ERROR"
rfb_shared_tool: "ERROR"
rfb_config_tool: "ERROR"

##### CYCLER #####
cycler.src.rfb_battery_cycler.app.app_man: "INFO"
rfb_battery_cycler.app.app_man: "INFO"
rfb_cycler_datatypes.cycler_data: "INFO"
mid.mid_str: "INFO"
mid.mid_dabs  : "INFO"
mid.mid_meas  : "INFO"
mid.mid_pwr   : "INFO"

file_handlers: {}