--- #YAML FILE START

__main__: "DEBUG"

##### app #####
app.app_man: "DEBUG"
app.app_diag: "DEBUG"

##### mid #####
mid.mid_dabs: "DEBUG"
mid.mid_meas: "DEBUG"
mid.mid_data: "DEBUG"
mid.mid_str: "DEBUG"

##### drv ######
rfb_driver_epc: 'WARNING'
rfb_driver_ea: 'INFO'
rfb_driver_rs: 'INFO'
rfb_driver_bases: 'INFO'
rfb_driver_bk: 'INFO'
rfb_driver_db: 'INFO'
rfb_driver_flow: 'INFO'
rfb_scpi_sniffer: 'INFO'
rfb_can_sniffer: 'INFO'

##### sys #####
rfb_shared_tool: "INFO"
rfb_config_tool: "INFO"
rfb_logger_tool: "INFO"

file_handlers: {
  # "log_can" : [ drv.drv_can, drv.drv_epc ],
}