---
#YAML FILE START
test_mid_dabs: "DEBUG"

__main__: "DEBUG"

##### DEV ######
cu_broker_client: "DEBUG"
cu_manager: "DEBUG"
detect: "DEBUG"
register: "DEBUG"

##### DRV ######
rfb_driver_epc: "DEBUG"
rfb_driver_db: "DEBUG"
rfb_driver_base : "DEBUG"
rfb_driver_bms: "DEBUG"
rfb_driver_flow : "DEBUG"
rfb_can_sniffer: "DEBUG"
rfb_scpi_sniffer: "DEBUG"

##### SYS #####
rfb_logger_tool: "DEBUG"
rfb_shared_tool: "DEBUG"
rfb_config_tool: "DEBUG"

##### CYCLER #####
cycler.src.rfb_battery_cycler.app.app_man: "DEBUG"
rfb_battery_cycler: "DEBUG"
rfb_cycler_datatypes: "DEBUG"
mid.mid_str: "DEBUG"
mid.mid_dabs  : "DEBUG"
mid.mid_meas  : "DEBUG"
mid.mid_pwr   : "DEBUG"

file_handlers: {}