# This workflow deploy system tools to development environment

name: Deployment of battery cycler drivers to development env

on:
  push:
    branches: [ "mid_data", "mid_meas", "mid_dabs", "mid_str",
                "mid_pwr", "app_diag", "app_man" ]

env:
  PACKAGE_NAME: wattrex-battery-cycler-controller

jobs:

  build-package:
    name: QA and Build battery controller on push
    uses: WattRex/System-Tools/.github/workflows/build_python_package.yml@develop
    with:
      package-name: "wattrex-battery-cycler-controller"
      python-version: "3.10"

  publish-package:
    name: Publish $PACKAGE_NAME package to Test PyPi
    needs: build-package
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      # strategy:
        #   fail-fast: false
        #   matrix:
          #     python-version: ["3.11"]

    steps:
      - name: Set environment variable
        run: |
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "${{ env.PACKAGE_NAME }}/dist/"
        shell: bash

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name:  "${{ env.PACKAGE_NAME }}"
          path: "${{ env.PACKAGE_NAME }}/dist/"

      - name: Publish package to Test PyPI
        uses: pypa/gh-action-pypi-publish@f8c70e705ffc13c3b4d1221169b84f12a75d6ca8
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository-url: https://test.pypi.org/projects/${{ env.PACKAGE_NAME }}
          packages-dir: "${{ env.PACKAGE_NAME }}/dist/"