# This workflow deploys battery cycler db_sync to development environment

name: Deployment of DB_SYNC

on:
  push:
    branches:
      - 'db_sync'

  pull_request_review:
    types: [submitted]

jobs:

  build-package-on-push:
    name: QA and Build ${{ vars.DB_SYNC_PACKAGE_NAME }} on push
    if: ${{ github.event_name == 'push' }}
    uses: WattRex/System-Tools/.github/workflows/build_python_package.yml@develop
    with:
      package-name: ${{ vars.DB_SYNC_PACKAGE_NAME }}
      package-path: "code/db_sync"
      source-path: "code/db_sync/src/wattrex_battery_cycler_db_sync"
      python-version: "3.10"

  build-package-on-pull-request:
    name: QA and Build ${{ vars.DB_SYNC_PACKAGE_NAME }} on pull request
    if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' && github.event.pull_request.head.ref == 'db_sync' }}
    uses: WattRex/System-Tools/.github/workflows/build_python_package.yml@develop
    with:
      package-name: ${{ vars.DB_SYNC_PACKAGE_NAME }}
      package-path: "code/db_sync"
      source-path: "code/db_sync/src/wattrex_battery_cycler_db_sync"
      python-version: "3.10"

  publish-package:
    name: Publish package ${{ vars.DB_SYNC_PACKAGE_NAME }} to PyPi
    needs: build-package-on-pull-request
    if: ${{ github.event_name == 'pull_request_review' && github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ vars.DB_SYNC_PACKAGE_NAME }}
          path: ${{ github.event.pull_request.head.ref }}/dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@f8c70e705ffc13c3b4d1221169b84f12a75d6ca8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: ${{ github.event.pull_request.head.ref }}/dist/