# This workflow deploys battery cycler controller to development environment

name: Deployment of battery cycler controller to development environment

on:
  push:
    branches:
      - "app_diag"
      - "app_man"
      - "mid_data"
      - "mid_meas"
      - "mid_dabs"
      - "mid_str"
      - "mid_pwr"

env:
  PACKAGE_NAME: wattrex-battery-cycler-controller

jobs:

  detect-folder:
    runs-on: ubuntu-latest
    steps:
      - name: "Set env variables"
        run: |
          echo "FOLDER=$(echo ${{ github.ref_name }} | cut -d'_' -f 1)" >> "$GITHUB_ENV"
          echo ${{ env.FOLDER }}

  build-package:
    name: QA and Build battery controller on ${{ github.ref_name }} push
    uses: WattRex/System-Tools/.github/workflows/build_python_package.yml@develop
    with:
      package-name: "${{ github.ref_name }}"
      package-path: "code/cycler/src/wattrex_battery_cycler/${{ env.FOLDER }}/${{ github.ref_name }}"
      requirements-path: "code/cycler"
      python-version: "3.10"

  publish-package:
    name: Publish wattrex-battery-cycler-controller package to Test PyPi
    needs: build-package
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write

    steps:
      - name: Set environment variable
        run: |
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "${{ env.PACKAGE_NAME }}/dist/"
        shell: bash

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name:  "${{ env.PACKAGE_NAME }}"
          path: "${{ env.PACKAGE_NAME }}/dist/"

      - name: Publish package to Test PyPI
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e #realse/v1.8.10
        with:
          verbose: true
          user: __token__
          password: ${{ secrets.PYPI_TEST_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: "${{ env.PACKAGE_NAME }}/dist/"
