# This workflow deploy system tools to development environment

name: Deployment of battery cycler drivers to development env

on:
  push:
    branches: [ "mid_data", "mid_meas", "mid_dabs", "mid_str",
                "mid_pwr", "app_diag", "app_man" ]

  pull_request_review:
    # types: [edited]
    review:
      state: [approved]
      pull_request:
        base:
          ref: [ "mid_data", "mid_meas", "mid_dabs", "mid_str",
                "mid_pwr", "app_diag", "app_man" ]

env:
  pacakge-name: wattrex-battery-cycler-controller

jobs:

  build-package-on-push:
    if: ${{ github.event_name == 'push'}}
    name: Build package on push ${{ github.ref_name }}
    uses: WattRex/System-Tools/.github/workflows/build_python_package.yml@develop
    with:
      package-name: $pacakge-name

  build-package-on-pull-request:
    if: ${{ github.event_name == 'pull_request_review' }}
    name: Build package  ${{ github.event.pull_request.head.ref }}
    uses: WattRex/System-Tools/.github/workflows/build_python_package.yml@develop
    with:
      package-name: $pacakge-name

  publish-package:

    name: Publish package ${{ github.event.pull_request.head.ref }} to PyPi
    if: ${{ github.event_name == 'pull_request_review' }}
    needs: build-package-on-pull-request
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      # strategy:
        #   fail-fast: false
        #   matrix:
          #     # python-version: ["3.7", "3.9", "3.11"]
          #     python-version: ["3.11"]

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: $pacakge-name
          path: "$pacakge-name/dist/"

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@f8c70e705ffc13c3b4d1221169b84f12a75d6ca8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: "$pacakge-name/dist/"
