# This workflow deploy system tools to development environment

name: Deployment of battery cycler drivers to development env

on:
  push:
    branches: [ "mid_data", "mid_meas", "mid_dabs", "mid_str",
                "mid_pwr", "app_diag", "app_man" ]

jobs:

  build-package-on-push:
    name: Build battery controller on push
    uses: WattRex/System-Tools/.github/workflows/build_python_package.yml@develop
    with:
      package-name: "wattrex-battery-controller"

  publish-package:

    name: Publish wattery-cycler-controller package to PyPi
    needs: build-package-on-push
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      # strategy:
        #   fail-fast: false
        #   matrix:
          #     # python-version: ["3.7", "3.9", "3.11"]
          #     python-version: ["3.11"]

    steps:
      - name: Set environment variable
        id: vars
        run: |
          echo "PACKAGE_NAME=wattrex-battery-controller" >> $GITHUB_ENV
        shell: bash

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name:  "${{ env.PACKAGE_NAME }}"
          path: "${{ env.PACKAGE_NAME }}/dist/"

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@f8c70e705ffc13c3b4d1221169b84f12a75d6ca8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: "${{ env.PACKAGE_NAME }}/dist/"
