# This workflow deploy system tools to production environment

name: Deploy cycler to Docker (PRODUCTION)

on:
  workflow_dispatch:
  
jobs:
  publish-docker-image-cycler:
    name: Publish cycler docker image
    uses: GIDEF-RFB/Battery-Experiments-Manager/.github/workflows/docker_image.yml@develop
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
    with:
      dockerfile-path: ./devops/cycler/Dockerfile.cycler
      docker-repo-name: rfb-cycler-node
      is-develop: false
      docker-user: ${{ vars.DOCKER_USER }}
      docker-user-arg: 69976 # wattrex
      docker-group-arg: 69976 # wattrex
      docker-target: cycler_prod
