# This is a basic workflow that is manually triggered

name: Manual cycler publish

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      is-production:
        description: 'If true publish package to PyPi else to TestPyPi'
        type: boolean
        default: false

jobs:
  build-package-on-request:
    name: Build package  "${{ vars.CYCLER_PACKAGE_NAME }}"
    uses: GIDEF-RFB/System-Tools/.github/workflows/build_python_package_fork_repo.yml@develop
    with:
      package-name: "${{ vars.CYCLER_PACKAGE_NAME }}"
      package-path: "code/cycler"
      source-path:  "code/cycler/src/${{ vars.CYCLER_PACKAGE_NAME }}"
      python-version: "3.10"
      is-test-package: ${{ !inputs.is-production }}

  publish-package:
    name: Publish package "${{ vars.CYCLER_PACKAGE_NAME }}" to PyPi or TestPyPi
    needs: build-package-on-request
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write

    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name:  ${{ vars.CYCLER_PACKAGE_NAME }}
          path: ${{ vars.CYCLER_PACKAGE_NAME }}/dist/

      - name: Publish package to PyPI
        if: ${{ inputs.is-production == true }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ${{ vars.CYCLER_PACKAGE_NAME }}/dist/

      - name: Publish package to TEST PyPI
        if: ${{ inputs.is-production == false }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          repository-url: https://test.pypi.org/legacy/
          packages-dir: ${{ vars.CYCLER_PACKAGE_NAME }}/dist/