# This is a basic workflow that is manually triggered

name: Manual publish extra pkg

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      is-production:
        description: 'If true publish package to PyPi else to TestPyPi'
        type: boolean
        default: false

jobs:
  publish-datatypes:
    if: ${{ github.ref_name }}=='datatypes'
    name: Build and publish datatypes package
    uses: ./.github/workflows/build_publish_extra_package.yml
    with:
      package-name: "${{ vars.DATATYPES_PACKAGE_NAME }}"
      package-path: "code/datatypes"
      source-path: "code/datatypes/src/${{ vars.DATATYPES_PACKAGE_NAME }}"
      is-production: ${{ inputs.is-production }}

  publish-db_sync-pkg-prod:
    if: ${{ github.ref_name }}=='db_sync'
    name: Build and publish db sync package
    uses: ./.github/workflows/build_publish_extra_package.yml
    with:
      package-name: "${{ vars.DB_SYNC_PACKAGE_NAME }}"
      package-path: "code/db_sync"
      source-path: "code/db_sync/src/${{ vars.DB_SYNC_PACKAGE_NAME }}"
      is-production: ${{ inputs.is-production }}

  publish-cu_manager-pkg-prod:
    if: ${{ github.ref_name }}=='cu_manager'
    name: Build and publish cu_manager package
    uses: ./.github/workflows/build_publish_extra_package.yml
    with:
      package-name: "${{ vars.CU_MANAGER_PACKAGE_NAME }}"
      package-path: "code/cu_manager"
      source-path: "code/cu_manager/src/${{ vars.CU_MANAGER_PACKAGE_NAME }}"
      is-production: ${{ inputs.is-production }}
