# This workflow will deploy in development environment the cycler controller module 

name: Deployment of battery cycler controller to real environment

on: workflow_call

env:
  ENV_CRED_TO_DEPLOY: ${{ secrets.ENV_CRED_TO_DEPLOY }}
  YAML_CRED_TO_DEPLOY: ${{ secrets.YAML_CRED_TO_DEPLOY }}
        
jobs:
  launch-real-bat:
    name: Launch cycler controller in real environment
    runs-on: [self-hosted, linux, ARM64, plc]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test to get var and secrets
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_VAR: ${{ vars.CYCLER_STATION_ID }}"
          echo "$ENV_CRED_TO_DEPLOY"
      - name: Copy repository content
        run: |
          rsync -av --progress ./ /tmp/wattrex-cycler-staging --exclude ./.git
          ls -lAh /tmp/wattrex-cycler-staging
      - name: Set secrets and log to deploy
        run: |
          echo "${{ secrets.ENV_CRED_TO_DEPLOY }}" > /tmp/wattrex-cycler-staging/devops/.cred.env
          cat /tmp/wattrex-cycler-staging/devops/.cred.env
          echo "${{ secrets.YAML_CRED_TO_DEPLOY }}" > /tmp/wattrex-cycler-staging/devops/.cred.yaml
          cat /tmp/wattrex-cycler-staging/devops/.cred.yaml
          echo "${{ vars.LOG_CONFIG }}" > /tmp/wattrex-cycler-staging/devops/log_config.yaml
          cat /tmp/wattrex-cycler-staging/devops/log_config.yaml
      - name: Rename test-file to tests_cycler.py
        run: |
          mv /tmp/wattrex-cycler-staging/code/cycler/tests/test_${{ github.event.pull_request.head.ref }}.py /tmp/wattrex-cycler-staging/code/cycler/tests/tests_cycler.py
          mv /tmp/wattrex-cycler-staging/code/cycler/tests/log_config_${{ github.event.pull_request.head.ref }}.yaml /tmp/wattrex-cycler-staging/devops/log_config.yaml
      - name: Execute deploy script
        run: |
          chmod +x /tmp/wattrex-cycler-staging/devops/deploy.sh
          /tmp/wattrex-cycler-staging/devops/deploy.sh
      - name: Execute deploy container
        id: pytest
        continue-on-error: true
        run: |
          /tmp/wattrex-cycler-staging/devops/deploy.sh test ${{ vars.CYCLER_STATION_ID }} ${{ github.event.pull_request.head.ref }}
      - name: Clean up
        run: |
          echo "${{ steps.pytest.outcome }}"
          /tmp/wattrex-cycler-staging/devops/deploy.sh force-stop
          mkdir -p ~/staging_tests
          rm -rf ~/staging_tests/logs_test_${{ github.event.pull_request.head.ref }}
          cp -r /tmp/wattrex-cycler-staging/log ~/staging_tests/logs_test_${{ github.event.pull_request.head.ref }}
          sudo rm -rf /tmp/wattrex-cycler-staging/
          docker image prune -f
          docker images -a
          ls -lAh /tmp
          if [ "${{ steps.pytest.outcome }}" = "failure" ]; then exit 1; fi
