# This workflow will deploy in development environment the cycler controller module 

name: Deployment of battery cycler controller to real environment

on: workflow_call

env:
  ENV_CRED_TO_DEPLOY: ${{ secrets.ENV_CRED_TO_DEPLOY }}
        
jobs:
  launch-real-bat:
    name: Launch cycler controller in real environment
    runs-on: [self-hosted, linux, ARM64, plc]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test to get var and secrets
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_VAR: ${{ vars.CYCLER_STATION_ID }}"
          echo "$ENV_CRED_TO_DEPLOY"
      - name: ls check
        run: |
          ls -lAh ./
          pwd
      - name: Build cycler docker image
        run: |
          docker build -t wattrex-cycler-node:latest -f ./devops/docker/Dockerfile.cycler .
          docker image ls -a
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - name: Build and export
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./devops/docker/Dockerfile.cycler
      #     tags: wattrex-cycler:latest
      #     outputs: type=docker,dest=/tmp/wattrex-cycler-local.tar
      #     push: false
      # - name: Download zip devops and docker image artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     path: /tmp
      # - name: Load docker image
      #   run: |
      #     docker load --input /tmp/wattrex-cycler-local.tar
      #     rm -f /tmp/wattrex-cycler-local.tar
      #     docker image ls -a
      #     ls -lAh /tmp
      # - name: Unzip devops
      #   run: |
      #     tar -xvf /tmp/wattrex-cycler-devops/wattrex-cycler-devops.tar -C /tmp
      #     rm -f /tmp/wattrex-cycler-devops/wattrex-cycler-devops.tar
      #     ls -lAh /tmp
      - name: Copy devops
        run: |
          cp -r ./devops /tmp/devops
          ls -lAh /tmp
      - name: Set secrets to deploy
        run: |
          echo "${{ secrets.ENV_CRED_TO_DEPLOY }}" > /tmp/devops/.cred.env
          cat /tmp/devops/.cred.env
      - name: Execute deploy script
        run: |
          chmod +x /tmp/devops/deploy.sh
          /tmp/devops/deploy.sh
      - name: Clean up
        run: |
          /tmp/devops/deploy.sh force-stop
          rm -rf /tmp/devops
          docker image prune -f
          ls -lAh /tmp